### PR TITLE
Alignment support

### PR DESCRIPTION
**Pull request by satishVekariya**
Set `alignment` property for **TopLeft**, **BottomLeft** and **CenterLeft** alignment.
 - default value 'centerLeft'

### CODE REVIEW

**Comment by filletofish** [comment]
@satishVekariya Thank you very much for contribution. 

Do you think there is a need for supporting different alignments, while one can simply use `spacing` to set alignment to _top_ or _bottom_?

**Comment by satishVekariya** [comment]
I think yes
Because its more readable and understandable. no one get direct idea about negative space, for that he/she need to understand code implementation.

**Comment by satishVekariya** [comment]
And also i think, Nothing is batter than something.

**Comment by satishVekariya** [comment]
See this https://itunes.apple.com/in/app/tastemade/id971197898?mt=8
Is this possible with `spacing` only?

**Comment by satishVekariya** [comment]
Even i am thinking that we can move spacing to enum's associated value to cover all alignment, Like 

```Swift

    public enum Alignment {
        case topLeft(spacing:CGFloat), topRight(spacing:CGFloat)
        case centerLeft(spacing:CGFloat), centerRight(spacing:CGFloat)
        case bottomLeft(spacing:CGFloat), bottomRight(spacing:CGFloat)
    }

```

**Comment by filletofish** [comment]
Hi @satishVekariya,

Excuse me for late response - was on vacation. If you are still interested in this PR I would express some points on proposed changes

I agree with your argument on not very clear name for `spacing` variable. Though I suppose adding such enum `Aligment` is a bit too much.  I would suggest rename it to `var offset: CGPoint`. So one can move car in both axis and still use clearer API. 

Also, it would be great if you have squashed your commits in one or two to keep commit history neat. You can take a look at this tutorial:
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

What do you think?

**Pull request closed without merging**
